In [1]:
import numpy as np
import pandas as pd

In [11]:
data = np.arange(364).reshape(52,7)
print (data)

[[  0   1   2   3   4   5   6]
 [  7   8   9  10  11  12  13]
 [ 14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34]
 [ 35  36  37  38  39  40  41]
 [ 42  43  44  45  46  47  48]
 [ 49  50  51  52  53  54  55]
 [ 56  57  58  59  60  61  62]
 [ 63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76]
 [ 77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97]
 [ 98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118]
 [119 120 121 122 123 124 125]
 [126 127 128 129 130 131 132]
 [133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146]
 [147 148 149 150 151 152 153]
 [154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167]
 [168 169 170 171 172 173 174]
 [175 176 177 178 179 180 181]
 [182 183 184 185 186 187 188]
 [189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202]
 [203 204 205 206 207 208 209]
 [210 211 212 213 214 215 216]
 [217 218 219 220 221 222 223]
 [224 22

In [13]:
data = np.arange(30).reshape(5,6)
print (data)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [15]:
data = np.arange(30).reshape(5,6)
print (data)

SyntaxError: invalid syntax (234679936.py, line 1)

In [25]:
print (data.shape)
print (data.ndim)

(5, 6)
2


In [83]:
data = np.arange(30,60).reshape(6,5)
print (data)

[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


In [37]:
data2=np.linspace(2,3),4
print (data2)

[2.         2.33333333 2.66666667 3.        ]


In [41]:
np.random.randint(10)


2

In [85]:
data2 = pd.DataFrame(data,index=['Row1',"row2","row3","row4","row5","row6"],
                    columns=["col1","col2","col3","col4","col5"]
                    )

In [77]:
print (data2)

      col1  col2  col3  col4  col5
Row1    30    31    32    33    34
row2    35    36    37    38    39
row3    40    41    42    43    44
row4    45    46    47    48    49
row5    50    51    52    53    54
row6    55    56    57    58    59


In [87]:
df  =data2
df.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5'], dtype='object')

In [89]:
df.shape

(6, 5)

In [93]:
df.head(2)

col1  col2  col3  col4  col5
Row1    30    31    32    33    34
row2    35    36    37    38    39

In [95]:
df.tail(2)

col1  col2  col3  col4  col5
row5    50    51    52    53    54
row6    55    56    57    58    59

In [99]:
df.sample()

col1  col2  col3  col4  col5
Row1    30    31    32    33    34

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Row1 to row6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    6 non-null      int32
 1   col2    6 non-null      int32
 2   col3    6 non-null      int32
 3   col4    6 non-null      int32
 4   col5    6 non-null      int32
dtypes: int32(5)
memory usage: 168.0+ bytes


In [115]:
df.describe()

col1       col2       col3       col4       col5
count   6.000000   6.000000   6.000000   6.000000   6.000000
mean   42.500000  43.500000  44.500000  45.500000  46.500000
std     9.354143   9.354143   9.354143   9.354143   9.354143
min    30.000000  31.000000  32.000000  33.000000  34.000000
25%    36.250000  37.250000  38.250000  39.250000  40.250000
50%    42.500000  43.500000  44.500000  45.500000  46.500000
75%    48.750000  49.750000  50.750000  51.750000  52.750000
max    55.000000  56.000000  57.000000  58.000000  59.000000

In [193]:
data = {
    'App': [f'App_{i}' for i in range(1, 31)],
    'Category': np.random.choice(['Game', 'Productivity', 'Health', 'Education'], 30),
    'Rating': np.random.uniform(1.0, 5.0, 30).round(1),
    'Reviews': np.random.randint(1, 10000, 30),
    'Size': np.random.choice(['Varies with device', '10M', '20M', '30M'], 30),
    'Installs': np.random.choice(['1,000+', '10,000+', '50,000+', '100,000+'], 30),
    'Type': np.random.choice(['Free', 'Paid'], 30),
    'Price': np.random.choice(['Free', '0.99', '1.99', '2.99', '4.99', '5.99', '9.99'], 30),
    'Content Rating': np.random.choice(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+'], 30)
}


In [195]:
df=pd.DataFrame(data)

In [197]:
print (df)

       App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1  Productivity     3.3     1442                 10M  100,000+  Paid   
1    App_2        Health     1.6     9739                 10M   50,000+  Paid   
2    App_3          Game     2.8     2794  Varies with device    1,000+  Free   
3    App_4          Game     2.7     9666                 10M   50,000+  Paid   
4    App_5          Game     2.5     9689                 10M  100,000+  Free   
5    App_6     Education     3.9     8944                 30M   50,000+  Free   
6    App_7  Productivity     1.2     1383  Varies with device   10,000+  Paid   
7    App_8  Productivity     1.5     1931  Varies with device    1,000+  Free   
8    App_9          Game     3.2     6972                 20M  100,000+  Paid   
9   App_10        Health     4.2     6595                 10M   50,000+  Paid   
10  App_11     Education     1.8     7726                 10M    1,000+  Free   
11  App_12  Productivity    

In [123]:
type(df)

pandas.core.frame.DataFrame

In [125]:
type(df.App)

pandas.core.series.Series

In [127]:
df.describe()

Rating      Reviews
count  30.000000    30.000000
mean    3.023333  5711.266667
std     1.072118  2836.391660
min     1.300000   698.000000
25%     2.100000  3300.250000
50%     2.850000  6764.000000
75%     3.850000  7888.000000
max     4.700000  9739.000000

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             30 non-null     object 
 1   Category        30 non-null     object 
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32  
 4   Size            30 non-null     object 
 5   Installs        30 non-null     object 
 6   Type            30 non-null     object 
 7   Price           30 non-null     object 
 8   Content Rating  30 non-null     object 
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB


In [131]:
df.head(1)

App Category  Rating  Reviews Size  Installs  Type Price Content Rating
0  App_1   Health     2.4     3484  10M  100,000+  Paid  5.99   Everyone 10+

In [133]:
df.sample(5)

App      Category  Rating  Reviews                Size  Installs  Type  \
11  App_12     Education     4.4     8521                 20M   10,000+  Free   
0    App_1        Health     2.4     3484                 10M  100,000+  Paid   
5    App_6        Health     2.1     6859                 20M   10,000+  Paid   
7    App_8     Education     1.7     7985                 30M    1,000+  Paid   
23  App_24  Productivity     4.7     1234  Varies with device    1,000+  Paid   

   Price Content Rating  
11  2.99     Mature 17+  
0   5.99   Everyone 10+  
5   4.99     Mature 17+  
7   4.99   Everyone 10+  
23  2.99   Everyone 10+

In [139]:
df[['App','Category','Price']]

App      Category Price
0    App_1        Health  5.99
1    App_2        Health  0.99
2    App_3        Health  4.99
3    App_4     Education     0
4    App_5  Productivity  1.99
5    App_6        Health  4.99
6    App_7     Education  1.99
7    App_8     Education  4.99
8    App_9          Game  4.99
9   App_10  Productivity  0.99
10  App_11        Health  9.99
11  App_12     Education  2.99
12  App_13     Education     0
13  App_14     Education  5.99
14  App_15        Health     0
15  App_16          Game  5.99
16  App_17  Productivity  0.99
17  App_18          Game  4.99
18  App_19          Game  1.99
19  App_20     Education  9.99
20  App_21     Education  9.99
21  App_22        Health  2.99
22  App_23          Game  1.99
23  App_24  Productivity  2.99
24  App_25        Health  1.99
25  App_26          Game     0
26  App_27  Productivity  1.99
27  App_28     Education  0.99
28  App_29          Game     0
29  App_30          Game  0.99

In [143]:
df.shape

(30, 9)

In [155]:
df['Category'].unique()

array(['Health', 'Education', 'Productivity', 'Game'], dtype=object)

In [163]:
df.isnull()

App  Category  Rating  Reviews   Size  Installs   Type  Price  \
0   False     False   False    False  False     False  False  False   
1   False     False   False    False  False     False  False  False   
2   False     False   False    False  False     False  False  False   
3   False     False   False    False  False     False  False  False   
4   False     False   False    False  False     False  False  False   
5   False     False   False    False  False     False  False  False   
6   False     False   False    False  False     False  False  False   
7   False     False   False    False  False     False  False  False   
8   False     False   False    False  False     False  False  False   
9   False     False   False    False  False     False  False  False   
10  False     False   False    False  False     False  False  False   
11  False     False   False    False  False     False  False  False   
12  False     False   False    False  False     False  False  False   
13  False     False   False    False  False     False  False  False   
14  False     False   False    False  False     False  False  False   
15  False     False   False    False  False     False  False  False   
16  False     False   False    False  False     False  False  False   
17  False     False   False    False  False     False  False  False   
18  False     False   False    False  False     False  False  False   
19  False     False   False    False  False     False  False  False   
20  False     False   False    False  False     False  False  False   
21  False     False   False    False  False     False  False  False   
22  False     False   False    False  False     False  False  False   
23  False     False   False    False  False     False  False  False   
24  False     False   False    False  False     False  False  False   
25  False     False   False    False  False     False  False  False   
26  False     False   False    False  False     False  False  False   
27  False     False   False    False  False     False  False  False   
28  False     False   False    False  False     False  False  False   
29  False     False   False    False  False     False  False  False   

    Content Rating  
0            False  
1            False  
2            False  
3            False  
4            False  
5            False  
6            False  
7            False  
8            False  
9            False  
10           False  
11           False  
12           False  
13           False  
14           False  
15           False  
16           False  
17           False  
18           False  
19           False  
20           False  
21           False  
22           False  
23           False  
24           False  
25           False  
26           False  
27           False  
28           False  
29           False

In [177]:
df.isnull().sum()


App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

In [199]:
df['Price'].unique()

array(['2.99', 'Free', '4.99', '1.99', '5.99', '0.99', '9.99'],
      dtype=object)

In [201]:
df['Price'] = df['Price'].replace('Free','0')

In [185]:
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1  Productivity     3.8     7496  Varies with device    1,000+  Paid   
1    App_2        Health     1.3     2767                 20M   50,000+  Free   
2    App_3     Education     4.7     5637                 10M   10,000+  Free   
3    App_4        Health     4.8     8348                 30M   50,000+  Free   
4    App_5        Health     4.5      581                 20M   50,000+  Paid   
5    App_6        Health     2.4     4711                 30M   50,000+  Paid   
6    App_7  Productivity     1.5     2912                 20M    1,000+  Paid   
7    App_8  Productivity     2.4     2789                 20M   10,000+  Paid   
8    App_9     Education     4.1     7709  Varies with device    1,000+  Free   
9   App_10          Game     2.9     4813                 30M   50,000+  Paid   
10  App_11          Game     1.3     7268                 10M   50,000+  Free   
11  App_12          Game     3.9     7009  Varies with device  100,000+  Paid   
12  App_13        Health     3.2     2330                 30M   10,000+  Paid   
13  App_14        Health     4.1     3188                 10M    1,000+  Paid   
14  App_15          Game     4.6      812  Varies with device   50,000+  Paid   
15  App_16  Productivity     1.3      699  Varies with device    1,000+  Paid   
16  App_17     Education     1.9     4100                 30M   10,000+  Paid   
17  App_18          Game     2.6     6587  Varies with device   10,000+  Paid   
18  App_19     Education     1.6     9219  Varies with device    1,000+  Paid   
19  App_20     Education     3.7     7989                 20M    1,000+  Paid   
20  App_21     Education     3.0     7543                 10M   50,000+  Free   
21  App_22  Productivity     1.7     3722                 20M    1,000+  Free   
22  App_23        Health     2.2     3790                 30M  100,000+  Paid   
23  App_24  Productivity     4.4     6054                 10M   10,000+  Paid   
24  App_25          Game     1.1     9767                 30M   50,000+  Paid   
25  App_26        Health     3.6     2949  Varies with device   10,000+  Free   
26  App_27        Health     1.9     7572                 30M   10,000+  Paid   
27  App_28     Education     3.4     5861                 10M   10,000+  Paid   
28  App_29        Health     4.7     1415                 30M   10,000+  Free   
29  App_30          Game     1.5      968  Varies with device   50,000+  Free   

   Price Content Rating  
0   4.99     Mature 17+  
1   0.99       Everyone  
2   4.99   Everyone 10+  
3   5.99   Everyone 10+  
4   5.99       Everyone  
5   5.99     Mature 17+  
6   0.99           Teen  
7   2.99           Teen  
8   9.99   Everyone 10+  
9   1.99   Everyone 10+  
10  4.99       Everyone  
11  2.99   Everyone 10+  
12     0           Teen  
13  1.99           Teen  
14  1.99           Teen  
15  1.99     Mature 17+  
16  4.99     Mature 17+  
17  4.99       Everyone  
18  5.99           Teen  
19  9.99   Everyone 10+  
20  2.99           Teen  
21  1.99   Everyone 10+  
22  9.99     Mature 17+  
23  9.99     Mature 17+  
24  0.99           Teen  
25     0           Teen  
26     0   Everyone 10+  
27  9.99     Mature 17+  
28  4.99       Everyone  
29  4.99       Everyone

In [187]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             30 non-null     object 
 1   Category        30 non-null     object 
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32  
 4   Size            30 non-null     object 
 5   Installs        30 non-null     object 
 6   Type            30 non-null     object 
 7   Price           30 non-null     object 
 8   Content Rating  30 non-null     object 
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB


In [203]:
df['Price'].unique()

array(['2.99', '0', '4.99', '1.99', '5.99', '0.99', '9.99'], dtype=object)